name: Build and test PRs

on: [pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      -  
        name: Checkout
        uses: actions/checkout@v3.1.0
      -  
        name: Setup .NET
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0'
      -  
        name: Run tests
        run: dotnet test -c Release
        
  docs:
    runs-on: ubuntu-latest

    steps:
      -  
        name: Checkout
        uses: actions/checkout@v3.1.0
      -  
        name: Build docs
        run: |
          yarn install
          yarn docs:build
